// See https://aka.ms/new-console-template for more information
using System.Text;

int numero = 34;
double notaPractica = 14;
int cantidad = (int)25.2;
bool isActive = false;
string nombre = "Pedro";
string nombre2 = "Eduardo";
byte a = 0b1111_1111;
long k = 0xAFD12;
double notaPracticaFinal = 14;
double notaParcial = 15;
double notaFinal = 20;
double  promedioFinal = (notaPracticaFinal + notaParcial + notaFinal) / 3;
int resultado = 20 * 30 + 12 * 11 - 12;
double division = 20 / 12;
double resto = 12 % 5;
double calculo = 2 * 5;
double resultado2 = division + resto - calculo;
StringBuilder cadena= new();
char c1 = 'b';
char c2 = 'B';
string s1 = "hola!";
string s2 = "Hola!";
string s3 = "hola!";
int result01 = 1 + 2 + 4 + 5;
int result02 = 11;
int  result03 = 3+8;
Console.WriteLine(c1 == c2);
Console.WriteLine(c1 == char.ToLower(c2));
Console.WriteLine(s1 == s2);
Console.WriteLine(s2 == s3);
Console.WriteLine("-----");
Console.WriteLine((result01 == result02) & (result02 == result03));
Console.WriteLine((result01 == result02) && (result02 == result03));
Console.WriteLine((result01 == result02) | (result02 == result03));
Console.WriteLine((result01 == result02) || (result02 == result03));
Console.WriteLine(numero);
Console.WriteLine(++numero);
Console.WriteLine(numero);
Console.WriteLine(--numero);
Console.WriteLine(notaPractica);
Console.WriteLine(cantidad);
Console.WriteLine(!isActive);
Console.WriteLine(nombre);
Console.WriteLine(nombre2);
Console.WriteLine(cadena.Append(nombre).Append(nombre2));
Console.WriteLine(a);
Console.WriteLine(k);
Console.WriteLine("El valor de k es {0:X}",k);
Console.WriteLine(Math.Round(promedioFinal,2));
Console.WriteLine(resultado);
Console.WriteLine(division);
Console.WriteLine(resto);
Console.WriteLine(calculo);
Console.WriteLine(resultado2.GetType());

bool masculino = true;
int edad = 18;
string mensaje02 = (!masculino || edad >= 18) ? "Mayor de edad o masculino" : "Femenino o menor de edad";
Console.WriteLine(mensaje02);
string nombre1 = "Marcos Hernandez";
Console.WriteLine(nombre1 == "MARCOS HERNANDEZ");
Console.WriteLine(nombre1.Equals("MARCOS HERNANDEZ", StringComparison.OrdinalIgnoreCase));
Console.WriteLine(nombre1.ToLower());
Console.WriteLine(nombre1.ToUpper());
string informacionUsuario = "Pedro Perez Castillo";
string informacionUsuarioSinEspacio = informacionUsuario.Trim();
Console.WriteLine(informacionUsuarioSinEspacio);
Console.WriteLine(informacionUsuario.Substring(6, 5));
Console.WriteLine(informacionUsuario.Substring(12, 8));
Console.WriteLine(informacionUsuario.Contains("Paredes"));
Console.WriteLine(informacionUsuario.Contains("Castillo"));
Console.WriteLine(informacionUsuario.Replace("Castillo","Guerrero"));
Console.WriteLine(informacionUsuario.Replace('e','i'));
string fullName = "Pedro-Perez-Castillo";
//fullName.Split("-") =>['Pedro','Perez','Castillo']
//                                     0            1           2
string nombres = fullName.Split("-")[0];
string apellidoPaterno = fullName.Split("-")[1];
string apellidoMaterno = fullName.Split("-")[2];
Console.WriteLine(nombres);
Console.WriteLine(apellidoPaterno);
Console.WriteLine(apellidoMaterno);
Console.WriteLine(fullName.StartsWith("P"));
Console.ReadLine();
